language: python

python:
  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install --only-binary=numpy,scipy 
  - pip install -r requirements.txt  
  - pip install nosetests

# command to run tests, e.g. python setup.py test
script: cd skfeature; nosetests
