name: unit-tests

on: [push, pull_request]
jobs:
  unit-test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.8, 3.9 ]
        os: [ ubuntu-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Test Python
        run: pytest --cov=./ --cov-report=xml --verbose --color=yes tests
      - name: Upload coverage to Codecov
        uses: irongut/CodeCoverageSummary@v1.0.1
        with:
          filename: ./coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'

